(function(g){var window=this;'use strict';var iPa=function(a,b){a.Na("onAutonavCoundownStarted",b)},w5=function(a,b,c){var d=b.ib();
g.N(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.Se(c?c:"mqdefault.jpg");var f=null,h=null;b instanceof g.UG&&(b.lengthText?(f=b.lengthText||null,h=b.By||null):b.lengthSeconds&&(f=g.ZL(b.lengthSeconds),h=g.ZL(b.lengthSeconds,!0)));var l=!!e;e=l&&"RD"===(new g.eN(e.substr(0,2),e.substr(2))).type;var m=b instanceof g.UG?b.isLivePlayback:null,n=b instanceof g.UG?b.isUpcoming:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:
b.author,aria_label:b.Tq||g.GI("\u041f\u043e\u0441\u043c\u043e\u0442\u0440\u0435\u0442\u044c $TITLE",{TITLE:b.title}),duration:f,timestamp:h,url:b.fn(),is_live:m,is_upcoming:n,is_list:l,is_mix:e,background:c?"background-image: url("+c+")":"",views_and_publish_time:d.shortViewCount?d.shortViewCount+" \u2022 "+d.publishedTimeText:d.publishedTimeText,autoplayAlternativeHeader:b.Lt};b instanceof g.fN&&(d.playlist_length=b.length);a.update(d)},x5=function(a){var b=a.T(),c=b.l;
g.V.call(this,{D:"a",K:"ytp-autonav-suggestion-card",U:{href:"{{url}}",target:c?b.G:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},S:[{D:"div",Ea:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],U:{style:"{{background}}"},S:[{D:"div",U:{"aria-label":"{{timestamp}}"},Ea:["ytp-autonav-timestamp"],ra:"{{duration}}"},{D:"div",Ea:["ytp-autonav-live-stamp"],ra:"\u0412 \u044d\u0444\u0438\u0440\u0435"},
{D:"div",Ea:["ytp-autonav-upcoming-stamp"],ra:"\u0421\u043a\u043e\u0440\u043e \u0432 \u044d\u0444\u0438\u0440\u0435"},{D:"div",K:"ytp-autonav-list-overlay",S:[{D:"div",K:"ytp-autonav-mix-text",ra:"\u041c\u0438\u043a\u0441"},{D:"div",K:"ytp-autonav-mix-icon"}]}]},{D:"div",Ea:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],ra:"{{title}}"},{D:"div",Ea:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],ra:"{{author}}"},{D:"div",Ea:["ytp-autonav-endscreen-upnext-author",
"ytp-autonav-view-and-date-card"],ra:"{{views_and_publish_time}}"}]});this.I=a;this.suggestion=null;this.i=c;this.Pa("click",this.onClick);this.Pa("keypress",this.l)},z5=function(a,b){b=void 0===b?!1:b;
g.V.call(this,{D:"div",K:"ytp-autonav-endscreen-countdown-container"});var c=this;this.C=b;this.l=0;b=a.T();var d=b.l;this.I=a;this.suggestion=null;this.i=new g.V({D:"div",K:"ytp-autonav-endscreen-upnext-container",U:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},S:[{D:"div",K:"ytp-autonav-endscreen-upnext-header"},{D:"div",K:"ytp-autonav-endscreen-upnext-alternative-header",ra:"{{autoplayAlternativeHeader}}"},
{D:"a",K:"ytp-autonav-endscreen-link-container",U:{href:"{{url}}",target:d?b.G:""},S:[{D:"div",K:"ytp-autonav-endscreen-upnext-thumbnail",U:{style:"{{background}}"},S:[{D:"div",U:{"aria-label":"{{timestamp}}"},Ea:["ytp-autonav-timestamp"],ra:"{{duration}}"},{D:"div",Ea:["ytp-autonav-live-stamp"],ra:"\u0412 \u044d\u0444\u0438\u0440\u0435"},{D:"div",Ea:["ytp-autonav-upcoming-stamp"],ra:"\u0421\u043a\u043e\u0440\u043e \u0432 \u044d\u0444\u0438\u0440\u0435"}]},{D:"div",K:"ytp-autonav-endscreen-video-info",
S:[{D:"div",K:"ytp-autonav-endscreen-premium-badge"},{D:"div",K:"ytp-autonav-endscreen-upnext-title",ra:"{{title}}"},{D:"div",K:"ytp-autonav-endscreen-upnext-author",ra:"{{author}}"},{D:"div",K:"ytp-autonav-view-and-date",ra:"{{views_and_publish_time}}"},{D:"div",K:"ytp-autonav-author-and-view",ra:"{{author_and_views}}"}]}]}]});g.J(this,this.i);this.i.Ba(this.element);d||this.N(this.i.Da("ytp-autonav-endscreen-link-container"),"click",this.qG);this.I.Yb(this.element,this,115127);this.I.Yb(this.i.Da("ytp-autonav-endscreen-link-container"),
this,115128);this.overlay=new g.V({D:"div",K:"ytp-autonav-overlay"});g.J(this,this.overlay);this.overlay.Ba(this.element);this.u=new g.V({D:"div",K:"ytp-autonav-endscreen-button-container"});g.J(this,this.u);this.u.Ba(this.element);this.cancelButton=new g.V({D:"button",Ea:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button"],U:{"aria-label":"\u041e\u0442\u043c\u0435\u043d\u0438\u0442\u044c \u0430\u0432\u0442\u043e\u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435"},
ra:"\u041e\u0442\u043c\u0435\u043d\u0430"});g.J(this,this.cancelButton);this.cancelButton.Ba(this.u.element);this.cancelButton.Pa("click",this.vO,this);this.I.Yb(this.cancelButton.element,this,115129);this.playButton=new g.V({D:"a",Ea:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button"],U:{href:"{{url}}",role:"button","aria-label":"\u0412\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0441\u0442\u0438 \u0441\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435 \u0432\u0438\u0434\u0435\u043e"},
ra:"\u0412\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0441\u0442\u0438"});g.J(this,this.playButton);this.playButton.Ba(this.u.element);this.playButton.Pa("click",this.qG,this);this.I.Yb(this.playButton.element,this,115130);this.B=new g.K(function(){y5(c)},500);
g.J(this,this.B);this.pG();this.N(a,"autonavvisibility",this.pG)},C5=function(a){var b=a.I.dj(!0,a.I.isFullscreen());
g.N(a.element,"ytp-autonav-endscreen-small-mode",a.jf(b));g.N(a.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.Qz);g.N(a.I.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.I.Sd());g.N(a.I.getRootNode(),"countdown-running",a.Gh());g.N(a.element,"ytp-player-content",a.I.Sd());g.zl(a.overlay.element,{width:b.width+"px"});if(!a.Gh()){a.I.Sd()?A5(a,Math.round(B5(a)/1E3)):A5(a);b=!!a.suggestion&&!!a.suggestion.Lt;var c=a.I.Sd()||!b;g.N(a.element,"ytp-autonav-endscreen-upnext-alternative-header-only",
!c&&b);g.N(a.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.cL(a.u,a.I.Sd())}},y5=function(a){var b=B5(a),c=Math,d=c.min;
var e=a.l?Date.now()-a.l:0;c=d.call(c,e,b);A5(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Gh()?a.select(!0):a.Gh()&&a.B.start()},B5=function(a){var b=a.I.gp();
return 0<=b?b:g.T(a.I.T().experiments,"autoplay_time")||1E4},A5=function(a,b){b=void 0===b?-1:b;
a=a.i.Da("ytp-autonav-endscreen-upnext-header");g.sg(a);if(0<=b){b=String(b);var c="\u0412\u0438\u0434\u0435\u043e \u043d\u0430\u0447\u043d\u0435\u0442\u0441\u044f \u0447\u0435\u0440\u0435\u0437 $SECONDS".match(/\$SECONDS/gi)[0],d="\u0412\u0438\u0434\u0435\u043e \u043d\u0430\u0447\u043d\u0435\u0442\u0441\u044f \u0447\u0435\u0440\u0435\u0437 $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.rg("\u0412\u0438\u0434\u0435\u043e \u043d\u0430\u0447\u043d\u0435\u0442\u0441\u044f \u0447\u0435\u0440\u0435\u0437 $SECONDS".slice(0,
d)));var e=g.qg("span");g.Kq(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.xg(e,b);a.appendChild(e);a.appendChild(g.rg("\u0412\u0438\u0434\u0435\u043e \u043d\u0430\u0447\u043d\u0435\u0442\u0441\u044f \u0447\u0435\u0440\u0435\u0437 $SECONDS".slice(d+c.length)));return}}g.xg(a,"\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435")},D5=function(a,b){g.V.call(this,{D:"div",
Ea:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},F5=function(a){g.V.call(this,{D:"div",
Ea:["ytp-upnext","ytp-player-content"],U:{"aria-label":"{{aria_label}}"},S:[{D:"div",K:"ytp-cued-thumbnail-overlay-image",U:{style:"{{background}}"}},{D:"span",K:"ytp-upnext-top",S:[{D:"span",K:"ytp-upnext-header",ra:"\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435"},{D:"span",K:"ytp-upnext-title",ra:"{{title}}"},{D:"span",K:"ytp-upnext-author",ra:"{{author}}"}]},{D:"a",K:"ytp-upnext-autoplay-icon",U:{role:"button",href:"{{url}}","aria-label":"\u0412\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0441\u0442\u0438 \u0441\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435 \u0432\u0438\u0434\u0435\u043e"},
S:[{D:"svg",U:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},S:[{D:"circle",K:"ytp-svg-autoplay-circle",U:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{D:"circle",K:"ytp-svg-autoplay-ring",U:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{D:"path",K:"ytp-svg-fill",U:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{D:"span",K:"ytp-upnext-bottom",
S:[{D:"span",K:"ytp-upnext-cancel"},{D:"span",K:"ytp-upnext-paused",ra:"\u0410\u0432\u0442\u043e\u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435 \u043f\u0440\u0438\u043e\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u043e."}]}]});this.api=a;this.cancelButton=null;this.C=this.Da("ytp-svg-autoplay-ring");this.u=this.notification=this.i=this.suggestion=null;this.B=new g.K(this.ix,5E3,this);this.l=0;var b=this.Da("ytp-upnext-cancel");this.cancelButton=
new g.V({D:"button",Ea:["ytp-upnext-cancel-button","ytp-button"],U:{tabindex:"0","aria-label":"\u041e\u0442\u043c\u0435\u043d\u0438\u0442\u044c \u0430\u0432\u0442\u043e\u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435"},ra:"\u041e\u0442\u043c\u0435\u043d\u0430"});g.J(this,this.cancelButton);this.cancelButton.Pa("click",this.wO,this);this.cancelButton.Ba(b);this.cancelButton&&this.api.Yb(this.cancelButton.element,this,115129);g.J(this,this.B);this.api.Yb(this.element,
this,18788);b=this.Da("ytp-upnext-autoplay-icon");this.N(b,"click",this.xO);this.api.Yb(b,this,115130);this.rG();this.N(a,"autonavvisibility",this.rG);this.N(a,"mdxnowautoplaying",this.rT);this.N(a,"mdxautoplaycanceled",this.sT);this.N(a,"mdxautoplayupnext",this.HM);E5(this)&&(a=(a=g.WM(this.api.sb()))?a.wQ():null)&&this.HM(a);g.N(this.element,"ytp-upnext-mobile",this.api.T().i)},E5=function(a){return 3===a.api.getPresentingPlayerType()},jPa=function(a,b){return b?b:0<=a.api.gp()?a.api.gp():g.T(a.api.T().experiments,
"autoplay_time")||1E4},G5=function(a,b){b=jPa(a,b);
var c=Math,d=c.min;var e=(0,g.P)()-a.l;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.C.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Gh()&&!E5(a)?a.select(!0):a.Gh()&&a.i.start()},H5=function(a){D5.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=this.suggestions=null;this.table=new g.V({D:"div",K:"ytp-suggestion-panel",S:[{D:"div",Ea:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],ra:"\u041f\u043e\u043a\u0430\u0437\u0430\u0442\u044c \u0434\u0440\u0443\u0433\u0438\u0435 \u0432\u0438\u0434\u0435\u043e"}]});this.J=new g.V({D:"div",K:"ytp-suggestions-container"});this.videos=[];this.u=null;this.C=this.G=!1;this.l=new z5(this.player);g.J(this,this.l);this.l.Ba(this.element);a.getVideoData().Zb?
this.i=this.l:(this.i=new F5(a),g.$M(this.player,this.i.element,4),g.J(this,this.i));this.overlay=new g.V({D:"div",K:"ytp-autonav-overlay-cancelled-state"});g.J(this,this.overlay);this.overlay.Ba(this.element);this.B=new g.cN(this);g.J(this,this.B);g.J(this,this.table);this.table.Ba(this.element);this.table.show();g.J(this,this.J);this.J.Ba(this.table.element);this.hide()},kPa=function(a,b){return g.Re(b.suggestions,function(c){c=g.AP(a.player.T(),c);
g.J(a,c);return c})},I5=function(a){var b=a.Sd();
b!==a.C&&(a.C=b,a.player.Z("autonavvisibility"),a.C?(a.l!==a.i&&a.l.hide(),a.table.hide()):(a.l!==a.i&&a.l.show(),a.table.show()))},J5=function(a){D5.call(this,a,"subscribecard-endscreen");
this.i=new g.V({D:"div",K:"ytp-subscribe-card",S:[{D:"img",K:"ytp-author-image",U:{src:"{{profilePicture}}"}},{D:"div",K:"ytp-subscribe-card-right",S:[{D:"div",K:"ytp-author-name",ra:"{{author}}"},{D:"div",K:"html5-subscribe-button-container"}]}]});g.J(this,this.i);this.i.Ba(this.element);var b=a.getVideoData();this.subscribeButton=new g.oO("\u041f\u043e\u0434\u043f\u0438\u0441\u0430\u0442\u044c\u0441\u044f",null,"\u041e\u0442\u043c\u0435\u043d\u0438\u0442\u044c \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0443",
null,!0,!1,b.Qi,b.subscribed,"trailer-endscreen",null,null,a);g.J(this,this.subscribeButton);this.subscribeButton.Ba(this.i.Da("html5-subscribe-button-container"));this.N(a,"videodatachange",this.Ma);this.Ma();this.hide()},K5=function(a){var b=a.T(),c=g.cj||g.Cl?{style:"will-change: opacity"}:void 0,d=b.l,e=["ytp-videowall-still"];
b.i&&e.push("ytp-videowall-show-text");g.V.call(this,{D:"a",Ea:e,U:{href:"{{url}}",target:d?b.G:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},S:[{D:"div",K:"ytp-videowall-still-image",U:{style:"{{background}}"}},{D:"span",K:"ytp-videowall-still-info",S:[{D:"span",K:"ytp-videowall-still-info-bg",S:[{D:"span",K:"ytp-videowall-still-info-content",U:c,S:[{D:"span",K:"ytp-videowall-still-info-title",ra:"{{title}}"},{D:"span",K:"ytp-videowall-still-info-author",
ra:"{{author_and_views}}"},{D:"span",K:"ytp-videowall-still-info-live",ra:"\u0412 \u044d\u0444\u0438\u0440\u0435"},{D:"span",K:"ytp-videowall-still-info-duration",ra:"{{duration}}"}]}]}]},{D:"span",Ea:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],S:[{D:"span",K:"ytp-videowall-still-listlabel-icon"},"\u041f\u043b\u0435\u0439\u043b\u0438\u0441\u0442",{D:"span",K:"ytp-videowall-still-listlabel-length",S:[" (",{D:"span",ra:"{{playlist_length}}"},")"]}]},{D:"span",Ea:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],S:[{D:"span",K:"ytp-videowall-still-listlabel-mix-icon"},"\u041c\u0438\u043a\u0441",{D:"span",K:"ytp-videowall-still-listlabel-length",ra:" (50+)"}]}]});this.suggestion=null;this.l=d;this.api=a;this.i=new g.cN(this);g.J(this,this.i);this.Pa("click",this.onClick);this.Pa("keypress",this.u);this.i.N(a,"videodatachange",this.ob);a.Kg(this.element,this);this.ob()},L5=function(a){D5.call(this,a,"videowall-endscreen");
var b=this;this.I=a;this.u=0;this.stills=[];this.B=this.videoData=this.suggestions=null;this.C=this.J=!1;this.L=null;this.l=new g.cN(this);g.J(this,this.l);this.G=new g.K(function(){g.M(b.element,"ytp-show-tiles")},0);
g.J(this,this.G);var c=new g.V({D:"button",Ea:["ytp-button","ytp-endscreen-previous"],U:{"aria-label":"\u041d\u0430\u0437\u0430\u0434"},S:[g.hL()]});g.J(this,c);c.Ba(this.element);c.Pa("click",this.BO,this);this.table=new g.$K({D:"div",K:"ytp-endscreen-content"});g.J(this,this.table);this.table.Ba(this.element);c=new g.V({D:"button",Ea:["ytp-button","ytp-endscreen-next"],U:{"aria-label":"\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435"},S:[g.iL()]});g.J(this,c);c.Ba(this.element);c.Pa("click",
this.AO,this);a.getVideoData().Zb?this.i=new z5(a,!0):this.i=new F5(a);g.J(this,this.i);g.$M(this.player,this.i.element,4);this.hide()},M5=function(a){return g.aN(a.player)&&a.Kt()&&!a.B},lPa=function(a,b){return g.Re(b.suggestions,function(c){c=g.AP(a.I.T(),c);
g.J(a,c);return c})},N5=function(a){var b=a.Sd();
b!==a.J&&(a.J=b,a.player.Z("autonavvisibility"))},O5=function(a){g.jN.call(this,a);
var b=this;this.endScreen=null;this.i=this.l=this.u=!1;this.listeners=new g.cN(this);g.J(this,this.listeners);this.env=a.T();mPa(a)?(this.u=!0,nPa(this),this.i?this.endScreen=new H5(a):this.endScreen=new L5(this.player)):this.env.Nc?this.endScreen=new J5(this.player):this.endScreen=new D5(this.player);g.J(this,this.endScreen);g.$M(this.player,this.endScreen.element,4);oPa(this);this.listeners.N(a,"videodatachange",this.ob,this);this.listeners.N(a,g.fA("endscreen"),function(c){b.Ad(c)});
this.listeners.N(a,g.gA("endscreen"),function(c){b.mf(c)})},nPa=function(a){var b=a.player.getVideoData();
if(!b||a.i===b.Hh&&a.l===b.Zb)return!1;a.i=b.Hh;a.l=b.Zb;return!0},mPa=function(a){a=a.T();
return a.zb&&!a.Nc},oPa=function(a){a.player.Ue("endscreen");
var b=a.player.getVideoData();b=new g.cA(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.cA(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});a.player.Gd([b,c])};
g.TM.prototype.gp=g.ca(2,function(){return this.app.gp()});
g.PX.prototype.gp=g.ca(1,function(){return this.getVideoData().qH});
g.w(x5,g.V);x5.prototype.select=function(){(this.I.Jj(this.suggestion.ib().videoId,this.suggestion.Nd,this.suggestion.getPlaylistId(),void 0,void 0,this.suggestion.nC||void 0)||this.I.X("web_player_endscreen_double_log_fix_killswitch"))&&this.I.Gb(this.element)};
x5.prototype.onClick=function(a){g.IN(a,this.I,this.i,this.suggestion.Nd||void 0)&&this.select()};
x5.prototype.l=function(a){switch(a.keyCode){case 13:case 32:g.ou(a)||(this.select(),g.nu(a))}};g.w(z5,g.V);g.k=z5.prototype;g.k.vt=function(a){this.suggestion!==a&&(this.suggestion=a,w5(this.i,a),this.playButton.Ra("url",this.suggestion.fn()),C5(this))};
g.k.Gh=function(){return 0<this.l};
g.k.Ds=function(){this.Gh()||(this.l=Date.now(),y5(this),iPa(this.I,B5(this)),g.N(this.I.getRootNode(),"countdown-running",this.Gh()))};
g.k.Sp=function(){this.lm();y5(this);var a=this.i.Da("ytp-autonav-endscreen-upnext-header");a&&g.xg(a,"\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435")};
g.k.lm=function(){this.Gh()&&(this.B.stop(),this.l=0)};
g.k.select=function(a){this.I.nextVideo(!1,void 0===a?!1:a);this.lm()};
g.k.qG=function(a){g.IN(a,this.I)&&(a.currentTarget===this.playButton.element?this.I.Gb(this.playButton.element):a.currentTarget===this.i.Da("ytp-autonav-endscreen-link-container")&&(a=this.i.Da("ytp-autonav-endscreen-link-container"),this.I.kb(a,!0),this.I.Gb(a)),this.select())};
g.k.vO=function(){this.I.Gb(this.cancelButton.element);g.VM(this.I,!0)};
g.k.pG=function(){var a=this.I.Sd();this.C&&this.xb!==a&&g.cL(this,a);C5(this);this.I.kb(this.element,a);this.I.kb(this.cancelButton.element,a);this.I.kb(this.i.Da("ytp-autonav-endscreen-link-container"),a);this.I.kb(this.playButton.element,a)};
g.k.jf=function(a){return 400>a.width||459>a.height};g.w(D5,g.V);g.k=D5.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.Kt=function(){return!1};
g.k.Sd=function(){return!1};
g.k.CJ=function(){return!1};g.w(F5,g.V);g.k=F5.prototype;g.k.ix=function(){this.notification&&(this.B.stop(),this.jc(this.u),this.u=null,this.notification.close(),this.notification=null)};
g.k.vt=function(a){this.suggestion=a;w5(this,a,"hqdefault.jpg")};
g.k.rG=function(){g.cL(this,this.api.Sd());this.api.kb(this.element,this.api.Sd());this.api.kb(this.Da("ytp-upnext-autoplay-icon"),this.api.Sd());this.cancelButton&&this.api.kb(this.cancelButton.element,this.api.Sd())};
g.k.BT=function(){window.focus();this.ix()};
g.k.Ds=function(a){var b=this;this.Gh()||(g.Su("a11y-announce","\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435 "+this.suggestion.title),this.l=(0,g.P)(),this.i=new g.K(function(){G5(b,a)},25),G5(this,a),iPa(this.api,jPa(this,a)));
g.Nq(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.V.prototype.hide.call(this)};
g.k.Gh=function(){return!!this.i};
g.k.Sp=function(){this.lm();this.l=(0,g.P)();G5(this);g.M(this.element,"ytp-upnext-autoplay-paused")};
g.k.lm=function(){this.Gh()&&(this.i.dispose(),this.i=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(g.S(this.api.T().experiments,"autonav_notifications")&&a&&window.Notification&&document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(b=this.suggestion.ib(),this.ix(),this.notification=new Notification("\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435",{body:b.title,icon:b.Se()}),this.u=this.N(this.notification,"click",this.BT),this.B.start())}this.lm();this.api.nextVideo(!1,
a)};
g.k.xO=function(a){!g.wg(this.cancelButton.element,g.ju(a))&&g.IN(a,this.api)&&(this.api.Sd()&&this.api.Gb(this.Da("ytp-upnext-autoplay-icon")),this.select())};
g.k.wO=function(){this.api.Sd()&&this.cancelButton&&this.api.Gb(this.cancelButton.element);g.VM(this.api,!0)};
g.k.rT=function(a){E5(this);this.show();this.Ds(a)};
g.k.HM=function(a){E5(this);this.suggestion&&this.suggestion.ib().videoId===a.ib().videoId||this.vt(a)};
g.k.sT=function(){E5(this);this.lm();this.hide()};
g.k.va=function(){this.lm();this.ix();g.V.prototype.va.call(this)};g.w(H5,D5);g.k=H5.prototype;g.k.create=function(){D5.prototype.create.call(this);this.B.N(this.player,"appresize",this.ut);this.B.N(this.player,"onVideoAreaChange",this.ut);this.B.N(this.player,"videodatachange",this.ob);this.B.N(this.player,"autonavchange",this.sG);this.B.N(this.player,"autonavcancel",this.yO);this.ob()};
g.k.show=function(){D5.prototype.show.call(this);(this.G||this.u&&this.u!==this.videoData.clientPlaybackNonce)&&g.VM(this.player,!1);g.aN(this.player)&&this.Kt()&&!this.u?(I5(this),2===this.videoData.autonavState?this.player.T().X("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.i.select(!0):this.i.Ds():3===this.videoData.autonavState&&this.i.Sp()):(g.VM(this.player,!0),I5(this));this.ut()};
g.k.hide=function(){D5.prototype.hide.call(this);this.i.Sp();I5(this)};
g.k.ut=function(){var a=this.player.dj(!0,this.player.isFullscreen());I5(this);C5(this.l);g.N(this.element,"ytp-autonav-cancelled-small-mode",this.jf(a));g.N(this.element,"ytp-autonav-cancelled-tiny-mode",this.sy(a));g.N(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.zl(this.overlay.element,{width:a.width+"px"});if(!this.C){a=g.r(this.videos.entries());for(var b=a.next();!b.done;b=a.next()){var c=g.r(b.value);b=c.next().value;c=c.next().value;g.N(c.element,
"ytp-suggestion-card-with-margin",1===b%2)}}};
g.k.ob=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((this.suggestions=kPa(this,a))&&this.suggestions.length)for(this.i.vt(this.suggestions[0]),this.i!==this.l&&this.l.vt(this.suggestions[0]),a=0;a<pPa.length;++a){var b=pPa[a];if(this.suggestions&&this.suggestions[b]){this.videos[a]=new x5(this.player);var c=this.videos[a];b=this.suggestions[b];c.suggestion!==b&&(c.suggestion=b,w5(c,b));g.J(this,this.videos[a]);this.videos[a].Ba(this.J.element)}}this.ut()}};
g.k.sG=function(a){1===a?(this.G=!1,this.u=this.videoData.clientPlaybackNonce,this.i.lm(),this.xb&&this.ut()):(this.G=!0,this.Sd()&&(2===a?this.i.Ds():3===a&&this.i.Sp()))};
g.k.yO=function(a){a?this.sG(1):(this.u=null,this.G=!1)};
g.k.Kt=function(){return 1!==this.videoData.autonavState};
g.k.jf=function(a){return(910>a.width||459>a.height)&&!this.sy(a)&&!(400>=a.width||360>=a.height)};
g.k.sy=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.Sd=function(){return this.xb&&g.aN(this.player)&&this.Kt()&&!this.u};
var pPa=[1,3,2,4];g.w(J5,D5);J5.prototype.Ma=function(){var a=this.player.getVideoData();this.i.update({profilePicture:a.Lh,author:a.author});this.subscribeButton.channelId=a.Qi;var b=this.subscribeButton;a.subscribed?b.l():b.u()};g.w(K5,g.V);K5.prototype.select=function(){(this.api.Jj(this.suggestion.ib().videoId,this.suggestion.Nd,this.suggestion.getPlaylistId(),void 0,void 0,this.suggestion.nC||void 0)||this.api.X("web_player_endscreen_double_log_fix_killswitch"))&&this.api.Gb(this.element)};
K5.prototype.onClick=function(a){g.IN(a,this.api,this.l,this.suggestion.Nd||void 0)&&this.select()};
K5.prototype.u=function(a){switch(a.keyCode){case 13:case 32:g.ou(a)||(this.select(),g.nu(a))}};
K5.prototype.ob=function(){var a=this.api.getVideoData(),b=this.api.T();this.l=a.C?!1:b.l};g.w(L5,D5);g.k=L5.prototype;g.k.create=function(){D5.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.suggestions=lPa(this,a),this.videoData=a);this.Xk();this.l.N(this.player,"appresize",this.Xk);this.l.N(this.player,"onVideoAreaChange",this.Xk);this.l.N(this.player,"videodatachange",this.ob);this.l.N(this.player,"autonavchange",this.YA);this.l.N(this.player,"autonavcancel",this.zO);a=this.videoData.autonavState;a!==this.L&&this.YA(a);this.l.N(this.element,"transitionend",this.UU)};
g.k.destroy=function(){g.Jx(this.l);g.gf(this.stills);this.stills=[];this.suggestions=null;D5.prototype.destroy.call(this);g.Nq(this.element,"ytp-show-tiles");this.G.stop();this.L=this.videoData.autonavState};
g.k.Kt=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){D5.prototype.show.call(this);g.Nq(this.element,"ytp-show-tiles");this.player.T().i?g.Gq(this.G):this.G.start();(this.C||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.VM(this.player,!1);M5(this)?(N5(this),2===this.videoData.autonavState?this.player.T().X("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.i.select(!0):this.i.Ds():3===this.videoData.autonavState&&this.i.Sp()):(g.VM(this.player,!0),N5(this))};
g.k.hide=function(){D5.prototype.hide.call(this);this.i.Sp();N5(this)};
g.k.UU=function(a){g.ju(a)===this.element&&this.Xk()};
g.k.Xk=function(){if(this.suggestions&&this.suggestions.length){g.M(this.element,"ytp-endscreen-paginate");var a=this.I.dj(!0,this.I.isFullscreen()),b=g.QM(this.I);b&&(b=b.Le()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),h=Math.max(a.height/54,2),l=this.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<h);){var p=b/2,q=e/2,t=b<=f-2&&n>=q*m,u=e<=h-2&&n>=p*m;if((p+1)/q*d/c>c/(p/(q+1)*d)&&u)n-=p*m,e+=2;else if(t)n-=
q*m,b+=2;else if(u)n-=p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m=Math.floor(Math.min(a.width,m*c));n=Math.floor(Math.min(a.height,n*c));a=this.table.element;g.Ol(a,m,n);g.zl(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});this.i.vt(this.suggestions[0]);this.i instanceof z5&&C5(this.i);g.N(this.element,"ytp-endscreen-takeover",M5(this));N5(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(h=0;h<e;h++)if(p=c,q=0,d&&f>=b-2&&h>=e-2?q=
1:0===h%2&&0===f%2&&(2>h&&2>f?0===h&&0===f&&(q=2):q=2),p=g.Pf(p+this.u,l),0!==q){t=this.stills[c];t||(t=new K5(this.player),this.stills[c]=t,a.appendChild(t.element));u=Math.floor(n*h/e);var x=Math.floor(m*f/b),y=Math.floor(n*(h+q)/e)-u-4,z=Math.floor(m*(f+q)/b)-x-4;g.Hl(t.element,x,u);g.Ol(t.element,z,y);g.zl(t.element,"transitionDelay",(h+f)/20+"s");g.N(t.element,"ytp-videowall-still-mini",1===q);g.N(t.element,"ytp-videowall-still-large",2<q);q=t;p=this.suggestions[p];q.suggestion!==p&&(q.suggestion=
p,t=q.api.T(),u=g.Lq(q.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",w5(q,p,u),g.rF(t)&&(t=p.fn(),t=g.ui(t,g.IM("emb_rel_end")),q.Ra("url",t)),(p=(p=p.Nd)&&p.itct)&&q.api.im(q.element,p));c++}g.N(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.ug(e.element),g.ff(e);this.stills.length=c}};
g.k.ob=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.u=0,this.suggestions=lPa(this,a),this.videoData=a,this.Xk())};
g.k.AO=function(){this.u+=this.stills.length;this.Xk()};
g.k.BO=function(){this.u-=this.stills.length;this.Xk()};
g.k.CJ=function(){return this.i.Gh()};
g.k.YA=function(a){1===a?(this.C=!1,this.B=this.videoData.clientPlaybackNonce,this.i.lm(),this.xb&&this.Xk()):(this.C=!0,this.xb&&M5(this)&&(2===a?this.i.Ds():3===a&&this.i.Sp()))};
g.k.zO=function(a){if(a){for(a=0;a<this.stills.length;a++)this.I.kb(this.stills[a].element,!0);this.YA(1)}else this.B=null,this.C=!1;this.Xk()};
g.k.Sd=function(){return this.xb&&M5(this)};g.w(O5,g.jN);g.k=O5.prototype;g.k.gq=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!mPa(this.player)||b;var c=a.ze||g.CF(a.B),d=this.player.wu();a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.Sd=function(){return this.endScreen.Sd()};
g.k.iR=function(){return this.Sd()?this.endScreen.CJ():!1};
g.k.va=function(){this.player.Ue("endscreen");g.jN.prototype.va.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.nH;if(b&&b.videoId){var c=this.player.sb().qd.get("heartbeat");a&&a.suggestions&&a.suggestions.length&&b.videoId===a.suggestions[0].id&&!a.QF?a=!1:(this.player.Jj(b.videoId,void 0,void 0,!0,!0,b),c&&c.Ey("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0)}else a=!1;a||(g.jN.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.jN.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.Ad=function(a){this.gq()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.mf=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.ob=function(){oPa(this);this.u&&nPa(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.i?this.endScreen=new H5(this.player):this.endScreen=new L5(this.player),g.J(this,this.endScreen),g.$M(this.player,this.endScreen.element,4))};g.uN.endscreen=O5;})(_yt_player);
