(function(g){var window=this;'use strict';var o6=function(a){g.V.call(this,{D:"div",K:"ytp-miniplayer-ui"});this.yf=!1;this.player=a;this.N(a,"minimized",this.fg);this.N(a,"onStateChange",this.VE)},p6=function(a){g.jN.call(this,a);
this.i=new o6(this.player);this.i.hide();g.$M(this.player,this.i.element,4);a.Be()&&(this.load(),g.N(a.getRootNode(),"ytp-player-minimized",!0))};
g.w(o6,g.V);g.k=o6.prototype;
g.k.iD=function(){this.tooltip=new g.FQ(this.player,this);g.J(this,this.tooltip);g.$M(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.pc=new g.eO(this.player);g.J(this,this.pc);this.qg=new g.V({D:"div",K:"ytp-miniplayer-scrim"});g.J(this,this.qg);this.qg.Ba(this.element);this.N(this.qg.element,"click",this.bz);var a=new g.V({D:"button",Ea:["ytp-miniplayer-close-button","ytp-button"],U:{"aria-label":"\u0417\u0430\u043a\u0440\u044b\u0442\u044c"},S:[g.jL()]});g.J(this,a);a.Ba(this.qg.element);
this.N(a.element,"click",this.wi);a=new g.M1(this.player,this);g.J(this,a);a.Ba(this.qg.element);this.Wo=new g.V({D:"div",K:"ytp-miniplayer-controls"});g.J(this,this.Wo);this.Wo.Ba(this.qg.element);this.N(this.Wo.element,"click",this.bz);var b=new g.V({D:"div",K:"ytp-miniplayer-button-container"});g.J(this,b);b.Ba(this.Wo.element);a=new g.V({D:"div",K:"ytp-miniplayer-play-button-container"});g.J(this,a);a.Ba(this.Wo.element);var c=new g.V({D:"div",K:"ytp-miniplayer-button-container"});g.J(this,c);
c.Ba(this.Wo.element);this.oL=new g.CP(this.player,this,!1);g.J(this,this.oL);this.oL.Ba(b.element);b=new g.zP(this.player,this);g.J(this,b);b.Ba(a.element);this.nextButton=new g.CP(this.player,this,!0);g.J(this,this.nextButton);this.nextButton.Ba(c.element);this.wg=new g.sQ(this.player,this);g.J(this,this.wg);this.wg.Ba(this.qg.element);this.Ic=new g.HP(this.player,this);g.J(this,this.Ic);g.$M(this.player,this.Ic.element,4);this.Oy=new g.V({D:"div",K:"ytp-miniplayer-buttons"});g.J(this,this.Oy);
g.$M(this.player,this.Oy.element,4);a=new g.V({D:"button",Ea:["ytp-miniplayer-close-button","ytp-button"],U:{"aria-label":"\u0417\u0430\u043a\u0440\u044b\u0442\u044c"},S:[g.jL()]});g.J(this,a);a.Ba(this.Oy.element);this.N(a.element,"click",this.wi);a=new g.V({D:"button",Ea:["ytp-miniplayer-replay-button","ytp-button"],U:{"aria-label":"\u0417\u0430\u043a\u0440\u044b\u0442\u044c"},S:[g.oL()]});g.J(this,a);a.Ba(this.Oy.element);this.N(a.element,"click",this.hU);this.N(this.player,"presentingplayerstatechange",
this.Hc);this.N(this.player,"appresize",this.tb);this.N(this.player,"fullscreentoggled",this.tb);this.tb()};
g.k.show=function(){this.yd=new g.Bq(this.Op,null,this);this.yd.start();this.yf||(this.iD(),this.yf=!0);0!==this.player.getPlayerState()&&g.V.prototype.show.call(this);this.Ic.show();this.player.unloadModule("annotations_module")};
g.k.hide=function(){this.yd&&(this.yd.dispose(),this.yd=void 0);g.V.prototype.hide.call(this);this.player.Be()||(this.yf&&this.Ic.hide(),this.player.loadModule("annotations_module"))};
g.k.va=function(){this.yd&&(this.yd.dispose(),this.yd=void 0);g.V.prototype.va.call(this)};
g.k.wi=function(){this.player.stopVideo();this.player.Na("onCloseMiniplayer")};
g.k.hU=function(){this.player.playVideo()};
g.k.bz=function(a){if(a.target===this.qg.element||a.target===this.Wo.element)g.S(this.player.T().experiments,"kevlar_miniplayer_play_pause_on_scrim")?g.mK(this.player.ub())?this.player.pauseVideo():this.player.playVideo():this.player.Na("onExpandMiniplayer")};
g.k.fg=function(){g.N(this.player.getRootNode(),"ytp-player-minimized",this.player.Be())};
g.k.jd=function(){this.Ic.Rb();this.wg.Rb()};
g.k.Op=function(){this.jd();this.yd&&this.yd.start()};
g.k.Hc=function(a){g.U(a.state,32)&&this.tooltip.hide()};
g.k.tb=function(){g.SP(this.Ic,0,this.player.Za().getPlayerSize().width,!1);g.JP(this.Ic)};
g.k.VE=function(a){this.player.Be()&&(0===a?this.hide():this.show())};
g.k.fc=function(){return this.tooltip};
g.k.Le=function(){return!1};
g.k.jf=function(){return!1};
g.k.di=function(){return!1};
g.k.Lz=function(){};
g.k.Mm=function(){};
g.k.rr=function(){};
g.k.cn=function(){return null};
g.k.dj=function(){return new g.pl(0,0,0,0)};
g.k.handleGlobalKeyDown=function(){return!1};
g.k.handleGlobalKeyUp=function(){return!1};
g.k.Vp=function(a,b,c,d,e){var f=0,h=d=0,l=g.Pl(a);if(b){c=g.Lq(b,"ytp-prev-button")||g.Lq(b,"ytp-next-button");var m=g.Lq(b,"ytp-play-button"),n=g.Lq(b,"ytp-miniplayer-expand-watch-page-button");c?f=h=12:m?(b=g.Nl(b,this.element),h=b.x,f=b.y-12):n&&(h=g.Lq(b,"ytp-miniplayer-button-top-left"),f=g.Nl(b,this.element),b=g.Pl(b),h?(h=8,f=f.y+40):(h=f.x-l.width+b.width,f=f.y-20))}else h=c-l.width/2,d=25+(e||0);b=this.player.Za().getPlayerSize().width;e=f+(e||0);l=g.Of(h,0,b-l.width);e?(a.style.top=e+"px",
a.style.bottom=""):(a.style.top="",a.style.bottom=d+"px");a.style.left=l+"px"};
g.k.showControls=function(){};
g.k.Qk=function(){};
g.k.pk=function(){return!1};g.w(p6,g.jN);p6.prototype.create=function(){};
p6.prototype.Hi=function(){return!1};
p6.prototype.load=function(){this.player.hideControls();this.i.show()};
p6.prototype.unload=function(){this.player.showControls();this.i.hide()};g.uN.miniplayer=p6;})(_yt_player);
